name: Publish to npm

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Get latest version from package.json
        id: current_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Determine version update type
        id: version_update
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"#major"* ]]; then
            echo "update_type=major" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.head_commit.message }}" == *"#minor"* ]]; then
            echo "update_type=minor" >> $GITHUB_OUTPUT
          else
            echo "update_type=patch" >> $GITHUB_OUTPUT
          fi

      - name: Bump version and push tag
        id: version_bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version ${{ steps.version_update.outputs.update_type }} -m "Bump version to %s [skip ci]"
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          git push
          git push --tags

      - name: Build package
        run: npm run build
        
      - name: Generate TypeDoc documentation
        run: npm run docs
        
      - name: Commit updated documentation
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git diff-index --quiet HEAD || git commit -m "Update documentation for v${{ steps.version_bump.outputs.new_version }} [skip ci]"
          git push

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version_bump.outputs.new_version }}
          release_name: Release v${{ steps.version_bump.outputs.new_version }}
          body: |
            Release of version ${{ steps.version_bump.outputs.new_version }}
            
            Automatic release created by GitHub Actions workflow.
            To see details of changes, please refer to the commit history.
            
            [View updated documentation](https://github.com/YoruAkio/kiutils/tree/main/docs)
          draft: false
          prerelease: false